"""Add academic_year_id to transactions

Revision ID: 4273146526df
Revises: 902ff9c748f8
Create Date: 2026-07-28 14:27:03.061479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4273146526df'
down_revision: Union[str, Sequence[str], None] = '902ff9c748f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bills_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_foreign_key('fk_bills_academic_year_id', 'academic_years', ['academic_year_id'], ['id'])
        batch_op.drop_column('due_date')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_foreign_key('fk_events_academic_year_id', 'academic_years', ['academic_year_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_foreign_key('fk_payments_academic_year_id', 'academic_years', ['academic_year_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_academic_year_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_academic_year_id'))
        batch_op.drop_column('academic_year_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_academic_year_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_events_academic_year_id'))
        batch_op.drop_column('academic_year_id')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DATE(), nullable=True))
        batch_op.drop_constraint('fk_bills_academic_year_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bills_academic_year_id'))
        batch_op.drop_column('academic_year_id')

    # ### end Alembic commands ###
