"""add_academic_years_bill_categories_student_status_payment_status

Revision ID: 902ff9c748f8
Revises: 9ca56c617887
Create Date: 2026-07-26 21:53:22.278050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '902ff9c748f8'
down_revision: Union[str, Sequence[str], None] = '9ca56c617887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_years_name'), ['name'], unique=True)

    op.create_table('bill_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_categories_code'), ['code'], unique=True)

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bills_category_id'), ['category_id'], unique=False)
        batch_op.create_foreign_key('fk_bills_category_id', 'bill_categories', ['category_id'], ['id'])

    payment_status_enum = sa.Enum('pending', 'paid', 'failed', 'expired', 'cancelled', 'refunded', name='paymentstatus')
    payment_status_enum.create(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', payment_status_enum, nullable=False, server_default='paid'))
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    with op.batch_alter_table('spp_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_spp_settings_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_foreign_key('fk_spp_settings_academic_year_id', 'academic_years', ['academic_year_id'], ['id'])

    student_status_enum = sa.Enum('active', 'graduated', 'transferred', 'dropout', 'inactive', name='studentstatus')
    student_status_enum.create(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', student_status_enum, nullable=False, server_default='active'))
        batch_op.create_index(batch_op.f('ix_students_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_students_academic_year_id', 'academic_years', ['academic_year_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_academic_year_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_status'))
        batch_op.drop_index(batch_op.f('ix_students_academic_year_id'))
        batch_op.drop_column('status')
        batch_op.drop_column('academic_year_id')

    with op.batch_alter_table('spp_settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_spp_settings_academic_year_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_spp_settings_academic_year_id'))
        batch_op.drop_column('academic_year_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bills_category_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_bills_category_id'))
        batch_op.drop_column('category_id')

    with op.batch_alter_table('bill_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_categories_code'))

    op.drop_table('bill_categories')
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_years_name'))

    op.drop_table('academic_years')
    sa.Enum(name='paymentstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='studentstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
