"""Initial B-03 models

Revision ID: 9ca56c617887
Revises: 
Create Date: 2026-07-25 14:39:14.711433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ca56c617887'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('account_holder', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_settings_key'), ['key'], unique=True)

    op.create_table('spp_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_nominal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nis', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('birth_place', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('academic_year', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_nis'), ['nis'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('per_student_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_target', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_collected', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'cancelled', name='eventstatus'), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('allow_installment', sa.Boolean(), nullable=False),
    sa.Column('min_installment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parent_student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_student_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_student_student_id'), ['student_id'], unique=False)

    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('bill_type', sa.Enum('spp', 'non_spp', 'event', name='billtype'), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('attachment_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'partial', 'paid', name='billstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bills_bill_type'), ['bill_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_student_id'), ['student_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.Enum('spp', 'non_spp', 'event', name='paymenttype'), nullable=False),
    sa.Column('spp_month', sa.Integer(), nullable=True),
    sa.Column('spp_year', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('infaq_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('cash', 'transfer', name='paymentmethod'), nullable=False),
    sa.Column('channel', sa.Enum('gateway', 'manual', name='paymentchannel'), nullable=False),
    sa.Column('gateway_transaction_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_type'), ['payment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_student_id'), ['student_id'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('pdf_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('void_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voided_by', sa.Integer(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_payment_id'), ['payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_receipts_receipt_number'), ['receipt_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_receipts_payment_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_student_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_type'))
        batch_op.drop_index(batch_op.f('ix_payments_bill_id'))

    op.drop_table('payments')
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_student_id'))
        batch_op.drop_index(batch_op.f('ix_bills_status'))
        batch_op.drop_index(batch_op.f('ix_bills_bill_type'))

    op.drop_table('bills')
    with op.batch_alter_table('parent_student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_student_student_id'))
        batch_op.drop_index(batch_op.f('ix_parent_student_parent_id'))

    op.drop_table('parent_student')
    op.drop_table('events')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_nis'))

    op.drop_table('students')
    op.drop_table('spp_settings')
    with op.batch_alter_table('school_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_settings_key'))

    op.drop_table('school_settings')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
